# 01-secret-opaque.yaml
# Create a basic Kubernetes secret
# WARNING: These values are only base64 encoded, NOT encrypted!
# Anyone with RBAC access to secrets can decode them
#
# To encode: echo -n "my_secret_password" | base64
# To decode: echo "bXlfc2VjcmV0X3Bhc3N3b3Jk" | base64 --decode

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devsecops-demo
  labels:
    app: devsecops-demo
type: Opaque
data:
  # base64 encoded values (NOT secure — just encoding)
  # echo -n "my_secret_password" | base64 → bXlfc2VjcmV0X3Bhc3N3b3Jk
  db-password: bXlfc2VjcmV0X3Bhc3N3b3Jk

  # echo -n "admin" | base64 → YWRtaW4=
  db-username: YWRtaW4=

  # echo -n "postgresql://admin:my_secret_password@db:5432/appdb" | base64
  db-connection-string: cG9zdGdyZXNxbDovL2FkbWluOm15X3NlY3JldF9wYXNzd29yZEBkYjo1NDMyL2FwcGRi
